### PR TITLE
Fixed printf "\033[H" error on nushell

### PR DESCRIPTION
**Pull request by wushuo894**
The following error occurs when I use [nushell](https://www.nushell.sh)

Error: nu::parser::parse_mismatch (link)

  × Parse mismatch during operation.
   ╭─[entry #1:1:1]
 1 │ printf "\033[H" 
   ·          ───┬──
   ·             ╰── expected supported escape character
   ╰────

### CODE REVIEW

**Comment by daltonmenezes** [comment]
Hi @W2725730722 , I believe your PR, as it is, will break other Shells, have you tried to add the **nushell** specific support? The [Contributing guide](https://github.com/daltonmenezes/hyper-init#contributing) can help you with it to update your PR properly. Thanks

**Comment by W2725730722** [comment]
> 嗨，@W2725730722我相信你的公关会破坏其他贝壳，你试过添加**nushell**特定的支持吗？[贡献指南](https://github.com/daltonmenezes/hyper-init#contributing)可以帮助您正确更新您的公关。谢谢

Ok, I'll add specific support for nushell

**Comment by wushuo894** [comment]
> Hi @W2725730722 , I believe your PR, as it is, will break other Shells, have you tried to add the **nushell** specific support? The [Contributing guide](https://github.com/daltonmenezes/hyper-init#contributing) can help you with it to update your PR properly. Thanks

Ok, I'll add specific support for nushell

**Review by daltonmenezes — APPROVED** [review]

**Comment by daltonmenezes** [comment]
Thanks @W2725730722 💜

**Pull request merged**
