### PR TITLE
add fish shell

### PR DESCRIPTION
**Pull request by jenhausu**
I add a fish shell for separator and clear command and fix some typo.

### CODE REVIEW

**Review by nightmarlin — COMMENTED** [review]
In `README.md` in `## Contributing`:
How about "relatively small shell dictionary?"
"relatively shell dictionary" sounds a bit weird

**Comment by jenhausu** [comment]
I don't know what is "small dictionary" mean? I thought that is just a typo.
Isn't author mean that separator and clear command can change base on the shell used currently?

**Comment by nightmarlin** [comment]
"Small" is not a typo in this case: It refers to the size of the data dictionary (it only contains 5 items therefore as far as dictionaries go it is small). Shell refers to the data stored within the dictionary

"is based on its relatively small shell dictionary" -> a short collection of shell data
"is based on its shell dictionary" -> a collection of shell data
"is based on its relatively shell dictionary" -> grammatically incorrect as a noun is being used an adjective

**Comment by jenhausu** [comment]
oh, understood. I'll change back to the original word.

**Pull request merged**
